/* ═══════════════════════════════════════════════════════
   campus.js — Monta Vista-inspired campus data
   Zones, NPCs, unlock conditions, adjacency graph
═══════════════════════════════════════════════════════ */

'use strict';

// ── School Day periods ────────────────────────────────
const PERIODS = [
  { id: 'before_school', label: 'Before School',  time: '7:30 AM',  free: true  },
  { id: 'period_1',      label: 'Period 1',        time: '8:30 AM',  free: false },
  { id: 'period_2',      label: 'Period 2',        time: '9:20 AM',  free: false },
  { id: 'period_3',      label: 'Period 3',        time: '10:40 AM', free: false },
  { id: 'brunch',        label: 'Brunch',          time: '11:25 AM', free: true  },
  { id: 'period_4',      label: 'Period 4',        time: '11:50 AM', free: false },
  { id: 'period_5',      label: 'Period 5',        time: '12:40 PM',  free: false },
  { id: 'lunch',         label: 'Lunch',           time: '1:25 PM', free: true  },
  { id: 'period_6',      label: 'Period 5',        time: '2:15 PM',  free: false },
  { id: 'period_7',      label: 'Period 6',        time: '3:05 PM',  free: false },
  { id: 'after_school',  label: 'After School',    time: '3:50 PM',  free: true  },
];

const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];

// ── Zone types and their map colors ──────────────────
const ZONE_TYPES = {
  outdoor:  { color: '#C8D8A8', border: '#8FA870', label: 'Outdoor' },
  building: { color: '#E8DDD0', border: '#B8A898', label: 'Building' },
  sports:   { color: '#C4D4B0', border: '#8AAA78', label: 'Sports' },
  special:  { color: '#E8D8B8', border: '#C4A870', label: 'Special' },
  hidden:   { color: '#D8C8B0', border: '#A89068', label: 'Hidden' },
};

// ── Campus zones ──────────────────────────────────────
// mapGrid: { col, row } — 1-indexed, 3-column × 6-row grid
const ZONES = [
  // ── Row 1: Front of campus ──────────────────────────
  {
    id: 'admin',
    name: 'Administration',
    shortName: 'Admin',
    description: "Counselor's office.",
    type: 'building',
    unlocksAt: 9,
    mapGrid: { col: 1, row: 1 },
    adjacent: ['main_quad', 'building_200', 'front_entrance'],
    freeTimeOnly: false,
    alwaysOpen: true,
    icon: '🏛',
    vibes: ['Counselors', 'Office Hours', 'Records'],
  },
  {
    id: 'front_entrance',
    name: 'Front Entrance',
    shortName: 'Front Gate',
    description: 'Where you arrive every morning.',
    type: 'outdoor',
    unlocksAt: 9,
    mapGrid: { col: 2, row: 1 },
    adjacent: ['admin', 'main_quad', 'junior_lot'],
    freeTimeOnly: false,
    alwaysOpen: true,
    icon: '🚪',
    vibes: ['Morning Arrivals', 'Flyers', 'Flagpole'],
  },
  {
    id: 'junior_lot',
    name: 'Junior Lot',
    shortName: 'Jr. Lot',
    description: "You can park here once you're an upperclassmen.",
    type: 'outdoor',
    unlocksAt: 11,
    mapGrid: { col: 3, row: 1 },
    adjacent: ['front_entrance', 'library'],
    freeTimeOnly: true,
    alwaysOpen: false,
    icon: '🚗',
    vibes: ['Cars', 'Freedom', 'Lunch Runs'],
  },

  // ── Row 2: Core campus ──────────────────────────────
  {
    id: 'building_200',
    name: '200 Building',
    shortName: '200s',
    description: 'Math. ',
    type: 'building',
    unlocksAt: 9,
    mapGrid: { col: 1, row: 2 },
    adjacent: ['admin', 'main_quad', 'building_100'],
    freeTimeOnly: false,
    alwaysOpen: false,
    icon: '🔢',
    vibes: ['Math', 'APs', 'Competition'],
  },
  {
    id: 'main_quad',
    name: 'Main Quad',
    shortName: 'The Quad',
    description: 'Everyone passes through here every period.',
    type: 'outdoor',
    unlocksAt: 9,
    mapGrid: { col: 2, row: 2 },
    adjacent: ['front_entrance', 'admin', 'building_200', 'library', 'building_100', 'cafeteria'],
    freeTimeOnly: false,
    alwaysOpen: true,
    icon: '☀️',
    vibes: ['Social Hub', 'Benches', 'Fountain'],
  },
  {
    id: 'library',
    name: 'Library',
    shortName: 'Library',
    description: 'The quietest part of school.',
    type: 'building',
    unlocksAt: 9,
    mapGrid: { col: 3, row: 2 },
    adjacent: ['front_entrance', 'main_quad', 'junior_lot', 'building_500'],
    freeTimeOnly: false,
    alwaysOpen: true,
    icon: '📚',
    vibes: ['Study', 'Quiet', 'Computers'],
  },

  // ── Row 3: Middle campus ────────────────────────────
  {
    id: 'building_100',
    name: '100 Building',
    shortName: '100s',
    description: "English, History, AP Lang, AP Gov.",
    type: 'building',
    unlocksAt: 9,
    mapGrid: { col: 1, row: 3 },
    adjacent: ['building_200', 'main_quad', 'cafeteria', 'building_300'],
    freeTimeOnly: false,
    alwaysOpen: false,
    icon: '✍️',
    vibes: ['English', 'History', 'Essays'],
  },
  {
    id: 'cafeteria',
    name: 'Cafeteria / MPR',
    shortName: 'Cafeteria',
    description: "Where you hangout with your friends.",
    type: 'building',
    unlocksAt: 9,
    mapGrid: { col: 2, row: 3 },
    adjacent: ['main_quad', 'building_100', 'building_400'],
    freeTimeOnly: false,
    alwaysOpen: true,
    icon: '🍽',
    vibes: ['Lunch Tables', 'Food Lines', 'Drama'],
  },
  {
    id: 'building_500',
    name: '500 Building',
    shortName: '500s',
    description: 'Spanish, Chinese, French, Japanese.',
    type: 'building',
    unlocksAt: 11,
    mapGrid: { col: 3, row: 3 },
    adjacent: ['library', 'building_400', 'auditorium'],
    freeTimeOnly: false,
    alwaysOpen: false,
    icon: '🌍',
    vibes: ['Languages', 'Culture', 'Exchange Students'],
  },

  // ── Row 4: Back campus ──────────────────────────────
  {
    id: 'building_300',
    name: '300 Building',
    shortName: '300s',
    description: 'Bio, Chem, Physics.',
    type: 'building',
    unlocksAt: 10,
    mapGrid: { col: 1, row: 4 },
    adjacent: ['building_100', 'cafeteria', 'gym'],
    freeTimeOnly: false,
    alwaysOpen: false,
    icon: '🔬',
    vibes: ['Science', 'Labs', 'Research'],
  },
  {
    id: 'building_400',
    name: '400 Building',
    shortName: '400s / Arts',
    description: 'Band, orchestra, choir, art, drama.',
    type: 'building',
    unlocksAt: 10,
    mapGrid: { col: 2, row: 4 },
    adjacent: ['cafeteria', 'building_300', 'auditorium', 'gym', 'behind_400s'],
    freeTimeOnly: false,
    alwaysOpen: false,
    icon: '🎨',
    vibes: ['Music', 'Art', 'Drama'],
  },
  {
    id: 'auditorium',
    name: 'Auditorium',
    shortName: 'Auditorium',
    description: 'Award ceremonies and talent shows.',
    type: 'building',
    unlocksAt: 11,
    mapGrid: { col: 3, row: 4 },
    adjacent: ['building_500', 'building_400', 'senior_quad'],
    freeTimeOnly: false,
    alwaysOpen: false,
    icon: '🎭',
    vibes: ['Performances', 'Rallies', 'Ceremonies'],
  },

  // ── Row 5: PE / Social ──────────────────────────────
  {
    id: 'gym',
    name: 'Gym',
    shortName: 'Gym',
    description: 'PE. The weight room in the back.',
    type: 'building',
    unlocksAt: 9,
    mapGrid: { col: 1, row: 5 },
    adjacent: ['building_300', 'building_400', 'locker_rooms', 'basketball_courts'],
    freeTimeOnly: false,
    alwaysOpen: false,
    icon: '🏋️',
    vibes: ['PE', 'Weight Room', 'Rallies'],
  },
  {
    id: 'senior_quad',
    name: 'Senior Quad',
    shortName: 'Senior Quad',
    description: "A small patio around the back.",
    type: 'outdoor',
    unlocksAt: 12,
    mapGrid: { col: 2, row: 5 },
    adjacent: ['auditorium', 'building_400', 'behind_400s'],
    freeTimeOnly: true,
    alwaysOpen: false,
    icon: '🌿',
    vibes: ['Seniors Only', 'Mural', 'Picnic Tables'],
  },
  {
    id: 'tennis_courts',
    name: 'Tennis Courts',
    shortName: 'Tennis',
    description: 'The varsity team has first priority.',
    type: 'sports',
    unlocksAt: 10,
    mapGrid: { col: 3, row: 5 },
    adjacent: ['building_500', 'baseball_diamond'],
    freeTimeOnly: true,
    alwaysOpen: false,
    icon: '🎾',
    vibes: ['Tennis Team', 'After School', 'Tryouts'],
  },

  // ── Row 6: Athletic fields ──────────────────────────
  {
    id: 'locker_rooms',
    name: 'PE Locker Rooms',
    shortName: 'Locker Rooms',
    description: "Loud and chaotic.",
    type: 'building',
    unlocksAt: 9,
    mapGrid: { col: 1, row: 6 },
    adjacent: ['gym', 'basketball_courts'],
    freeTimeOnly: false,
    alwaysOpen: false,
    icon: '🔑',
    vibes: ['PE', 'Changing', 'Unguarded'],
  },
  {
    id: 'basketball_courts',
    name: 'Basketball Courts',
    shortName: 'B-Courts',
    description: 'Outdoor courts near the gym.',
    type: 'sports',
    unlocksAt: 9,
    mapGrid: { col: 2, row: 6 },
    adjacent: ['gym', 'locker_rooms', 'athletic_field'],
    freeTimeOnly: true,
    alwaysOpen: false,
    icon: '🏀',
    vibes: ['Pickup Games', 'After School', 'Spectators'],
  },
  {
    id: 'athletic_field',
    name: 'Athletic Field / Track',
    shortName: 'The Track',
    description: 'The 400m track around the football field.',
    type: 'sports',
    unlocksAt: 11,
    mapGrid: { col: 3, row: 6 },
    adjacent: ['basketball_courts', 'baseball_diamond'],
    freeTimeOnly: true,
    alwaysOpen: false,
    icon: '🏃',
    vibes: ['Track', 'Football', 'Varsity'],
  },

  // ── Hidden / Special zones ──────────────────────────
  {
    id: 'behind_400s',
    name: 'Behind the 400s',
    shortName: 'Behind 400s',
    description: "A gap between the arts building and the back fence.",
    type: 'hidden',
    unlocksAt: 12,
    mapGrid: null,  // not shown on main map
    adjacent: ['building_400', 'senior_quad'],
    freeTimeOnly: true,
    alwaysOpen: false,
    icon: '🌿',
    vibes: ['Hidden', 'Private', 'Off the Record'],
  },
  {
    id: 'baseball_diamond',
    name: 'Baseball Diamond',
    shortName: 'Baseball',
    description: 'Maybe the best sport at Monta Vista',
    type: 'sports',
    unlocksAt: 10,
    mapGrid: null,  // accessible via athletic_field / tennis_courts
    adjacent: ['athletic_field', 'tennis_courts'],
    freeTimeOnly: true,
    alwaysOpen: false,
    icon: '⚾',
    vibes: ['Spring Season', 'Varsity Baseball'],
  },
];

// ── NPC shells ────────────────────────────────────────
// Dialogue is registered by story modules via Engine.addDialogue(npcId, tree)
const NPCS = [
  // ─ Staff ─────────────────────────────────────────
  /*
  {
    id: 'ms_chen',
    name: 'Ms. Chen',
    role: 'Counselor',
    portrait: '👩‍💼',
    defaultZone: 'admin',
    schedule: {
      before_school: 'admin', period_1: null, period_2: 'admin',
      brunch: 'admin', period_3: null, period_4: 'admin',
      lunch: 'cafeteria', period_5: 'admin', period_6: null,
      after_school: 'admin',
    },
    group: null,
    statRequirements: {},
  },
  {
    id: 'mr_okafor',
    name: 'Mr. Okafor',
    role: 'English Teacher',
    portrait: '👨‍🏫',
    defaultZone: 'building_100',
    schedule: {
      before_school: 'building_100', period_1: null, period_2: null,
      brunch: 'main_quad', period_3: null, period_4: null,
      lunch: 'cafeteria', period_5: null, period_6: null,
      after_school: 'building_100',
    },
    group: null,
    statRequirements: {},
  },
  {
    id: 'coach_thomas',
    name: 'Coach Thomas',
    role: 'PE / Track Coach',
    portrait: '👨‍🏫',
    defaultZone: 'gym',
    schedule: {
      before_school: 'gym', period_1: null, period_2: null,
      brunch: 'gym', period_3: null, period_4: null,
      lunch: 'gym', period_5: null, period_6: null,
      after_school: 'athletic_field',
    },
    group: null,
    statRequirements: {},
    orientationRole: 'speaker',
  },

  // ─ Students ───────────────────────────────────────
  {
    id: 'lucas',
    name: 'Lucas',
    role: 'Student',
    portrait: '🧑',
    defaultZone: 'library',
    schedule: {
      before_school: 'main_quad', period_1: null, period_2: null,
      brunch: 'main_quad', period_3: null, period_4: null,
      lunch: 'library', period_5: null, period_6: null,
      after_school: 'library',
    },
    group: 'grind',
    statRequirements: {},
  },
  {
    id: 'jayden',
    name: 'Jayden',
    role: 'Student',
    portrait: '🧑',
    defaultZone: 'main_quad',
    schedule: {
      before_school: 'front_entrance', period_1: null, period_2: null,
      brunch: 'main_quad', period_3: null, period_4: null,
      lunch: 'cafeteria', period_5: null, period_6: null,
      after_school: 'basketball_courts',
    },
    group: 'mob',
    statRequirements: {},
  },
  {
    id: 'priya',
    name: 'Priya',
    role: 'Student',
    portrait: '👩',
    defaultZone: 'building_400',
    schedule: {
      before_school: 'main_quad', period_1: null, period_2: null,
      brunch: 'building_400', period_3: null, period_4: null,
      lunch: 'cafeteria', period_5: null, period_6: null,
      after_school: 'auditorium',
    },
    group: 'balance',
    statRequirements: {},
  },
  {
    id: 'marcus',
    name: 'Marcus',
    role: 'Student',
    portrait: '🧑',
    defaultZone: 'gym',
    schedule: {
      before_school: 'athletic_field', period_1: null, period_2: null,
      brunch: 'basketball_courts', period_3: null, period_4: null,
      lunch: 'cafeteria', period_5: null, period_6: null,
      after_school: 'athletic_field',
    },
    group: 'mob',
    statRequirements: { athleticism: 4 },
  },
  {
    id: 'sofia',
    name: 'Sofia',
    role: 'Student',
    portrait: '👩',
    defaultZone: 'cafeteria',
    schedule: {
      before_school: 'front_entrance', period_1: null, period_2: null,
      brunch: 'main_quad', period_3: null, period_4: null,
      lunch: 'cafeteria', period_5: null, period_6: null,
      after_school: 'main_quad',
    },
    group: 'balance',
    statRequirements: {},
  },
  {
    id: 'danny',
    name: 'Danny',
    role: 'Student',
    portrait: '🧑',
    defaultZone: 'building_300',
    schedule: {
      before_school: 'library', period_1: null, period_2: null,
      brunch: 'library', period_3: null, period_4: null,
      lunch: 'library', period_5: null, period_6: null,
      after_school: 'building_300',
    },
    group: 'grind',
    statRequirements: { gpa: 6 },
  },
  {
    id: 'isabel',
    name: 'Isabel',
    role: 'Student',
    portrait: '👩',
    defaultZone: 'building_400',
    schedule: {
      before_school: 'behind_400s', period_1: null, period_2: null,
      brunch: 'building_400', period_3: null, period_4: null,
      lunch: 'behind_400s', period_5: null, period_6: null,
      after_school: 'building_400',
    },
    group: 'balance',
    statRequirements: {},
  },

  // ─ Orientation audience (freshmen at gym during before_school) ──────────
  {
    id: 'alex_chen',
    name: 'Alex',
    role: 'Freshman',
    portrait: '🧑',
    defaultZone: 'main_quad',
    schedule: {
      before_school: 'gym', period_1: null, period_2: null,
      brunch: 'main_quad', period_3: null, period_4: null,
      lunch: 'cafeteria', period_5: null, period_6: null,
      after_school: 'library',
    },
    group: 'grind',
    statRequirements: {},
    orientationRole: 'audience',
  },
  {
    id: 'tyler_park',
    name: 'Tyler',
    role: 'Freshman',
    portrait: '🧑',
    defaultZone: 'main_quad',
    schedule: {
      before_school: 'gym', period_1: null, period_2: null,
      brunch: 'main_quad', period_3: null, period_4: null,
      lunch: 'cafeteria', period_5: null, period_6: null,
      after_school: 'basketball_courts',
    },
    group: 'mob',
    statRequirements: {},
    orientationRole: 'audience',
  },
  {
    id: 'mia_torres',
    name: 'Mia',
    role: 'Freshman',
    portrait: '👩',
    defaultZone: 'main_quad',
    schedule: {
      before_school: 'gym', period_1: null, period_2: null,
      brunch: 'building_400', period_3: null, period_4: null,
      lunch: 'cafeteria', period_5: null, period_6: null,
      after_school: 'building_400',
    },
    group: 'balance',
    statRequirements: {},
    orientationRole: 'audience',
  },
  {
    id: 'devon_clark',
    name: 'Devon',
    role: 'Freshman',
    portrait: '🧑',
    defaultZone: 'basketball_courts',
    schedule: {
      before_school: 'gym', period_1: null, period_2: null,
      brunch: 'main_quad', period_3: null, period_4: null,
      lunch: 'cafeteria', period_5: null, period_6: null,
      after_school: 'basketball_courts',
    },
    group: 'mob',
    statRequirements: {},
    orientationRole: 'audience',
  },
  {
    id: 'naomi_walsh',
    name: 'Naomi',
    role: 'Freshman',
    portrait: '👩',
    defaultZone: 'library',
    schedule: {
      before_school: 'gym', period_1: null, period_2: null,
      brunch: 'library', period_3: null, period_4: null,
      lunch: 'library', period_5: null, period_6: null,
      after_school: 'library',
    },
    group: 'grind',
    statRequirements: {},
    orientationRole: 'audience',
  },
  {
    id: 'ryan_moss',
    name: 'Ryan',
    role: 'Freshman',
    portrait: '🧑',
    defaultZone: 'main_quad',
    schedule: {
      before_school: 'gym', period_1: null, period_2: null,
      brunch: 'main_quad', period_3: null, period_4: null,
      lunch: 'cafeteria', period_5: null, period_6: null,
      after_school: 'main_quad',
    },
    group: 'mob',
    statRequirements: {},
    orientationRole: 'audience',
  },
  */
];

// ── Interaction object shells ─────────────────────────
// Story modules register handlers via Engine.addInteraction()
// This list is the "world objects" that can always exist in zones
const WORLD_OBJECTS = [
  { id: 'bulletin_board',   zone: 'front_entrance', label: 'Check the bulletin board', icon: '📋' },
  { id: 'library_catalog',  zone: 'library',        label: 'Browse the catalog',       icon: '🔍' },
  { id: 'lunch_table',      zone: 'cafeteria',      label: 'Find a seat',              icon: '🪑' },
  { id: 'quad_bench',       zone: 'main_quad',      label: 'Sit for a while',          icon: '🪵' },
  { id: 'trophy_case',      zone: 'admin',          label: 'Look at the trophy case',  icon: '🏆' },
  { id: 'weight_room',      zone: 'gym',            label: 'Use the weight room',      icon: '💪' },
  { id: 'art_wall',         zone: 'building_400',   label: 'Look at the art wall',     icon: '🖼' },
  { id: 'practice_rooms',   zone: 'building_400',   label: 'Listen at the practice rooms', icon: '🎵' },
  { id: 'bleachers',        zone: 'gym',            label: 'Sit in the bleachers',     icon: '🪑' },
  { id: 'senior_mural',     zone: 'senior_quad',    label: 'Read the senior mural',    icon: '🎨' },
  { id: 'scoreboard',       zone: 'athletic_field', label: 'Check the scoreboard',     icon: '📊' },
  { id: 'science_lab',      zone: 'building_300',   label: 'Look at the lab setup',    icon: '🧪' },
];

// ── Grade advancement conditions ─────────────────────
// Story modules can add custom conditions via Engine.addGradeCondition()
// These are the structural defaults
const GRADE_CONDITIONS = {
  10: {
    description: 'Complete freshman year',
    minStats: { gpa: 3 },
    requiredFlags: ['freshman_year_complete'],  // must be explicitly set
  },
  11: {
    description: 'Complete sophomore year',
    minStats: { gpa: 3 },
    requiredFlags: [],
  },
  12: {
    description: 'Complete junior year',
    minStats: {},
    requiredFlags: [],
  },
};
